### ISSUE TITLE
Create Home page

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#16]
As a visitor, I want to see and inviting homepage with the key information so that I know what BestEvidence is.

## Acceptance Criteria
+ [x] Includes header & navigation area #18
- [x] Includes splash section with background image and buttons to link to create free account and learn more about BE
- [x] Includes How does it work section with 3 cards, search find and edit
- [x] Includes Testimonials section with 3 different testimonials - these must be easily edited by the admins
  + To think about: things like, can we make it so that just the text is editable and not the quotation marks for example (not worth spending more than 30mins on but think about the UX for a non-technical person)
- [x] Includes Redash information section with 3 cards - this will not be linked up to Redash at this stage but we can have a separate issue once our Product owner decides on the exact figures she wants here
- [x] Create Learn more section with link to learn more 
+ [x] Includes footer which includes #28 
  + Need Help? (no Forum link)
  + News (just latest publications page for now)
  + Copyright notice (BestEvidence, not 'Best Practice' as per designs)

**Comment by RobStallion** [comment]
Moving to please test. Will complete the header and footer sections in their respective issues.

**Comment by iteles** [comment]
There's something happening with the Redash area here.
Tested on Chrome 65.0.33 on Macbook:

<img width="1157" alt="screen shot 2018-03-28 at 14 54 35" src="https://user-images.githubusercontent.com/4185328/38033539-2a4db05a-3298-11e8-98cb-9365bd3504e6.png">

But it should look like:
<img width="1055" alt="screen shot 2018-03-28 at 14 59 32" src="https://user-images.githubusercontent.com/4185328/38033779-b14bfabc-3298-11e8-9114-ebe1a8e2bcba.png">

**Comment by iteles** [comment]
Also fixed with #43 

<img width="1126" alt="screen shot 2018-03-29 at 15 25 29" src="https://user-images.githubusercontent.com/4185328/38094364-755ea888-3365-11e8-9830-d2428b2caca5.png">
