### ISSUE TITLE
Create Pricing page

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#19]
- [x] Restyle the quodl pricing page 
- [x] Include section with button that links to contact page

**Comment by iteles** [comment]
A little additional whitespace on the sides as per the designs would be beneficial to the aesthetic flow here:
<img width="1280" alt="screen shot 2018-03-28 at 15 03 49" src="https://user-images.githubusercontent.com/4185328/38034053-553ad350-3299-11e8-90f2-a49cee1050e5.png">

**Comment by iteles** [comment]
Fixed! Looks like it was part of #43 
<img width="887" alt="screen shot 2018-03-29 at 15 24 38" src="https://user-images.githubusercontent.com/4185328/38094307-5a383b0a-3365-11e8-9679-57897ce79f42.png">
