### ISSUE TITLE
Create Publications Page

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#22]
- [x] Create page similar to Quodl blog 
- [x] Look into how client wants 'view all posts' to work, on Quodl this is done with pagination but in our designs, it looks as if the user would see all posts at once, currently no design for how viewing all posts would appear
Looking into search functionality first #21

**Comment by iteles** [comment]
@parkhabit I think the question you asked me this morning on this was slightly different to what is seems you're asking above. Could you pull out the question so I know I'm answering the right thing please? 😊

**Comment by parkhabit** [comment]
View all posts button will work by literally showing all the posts, as there is never going to be a huge number of publications.

**Comment by iteles** [comment]
This page errors and doesn't load (not a 404 like with http://best-evidence-site.herokuapp.com/blog for example).

**Comment by RobStallion** [comment]
[This line](https://github.com/dwyl/bestevidence-site/blob/master/lib/modules/apostrophe-blog-pages/views/index.html#L37) appears to be what is causing the pages to crash.

Will look into what is wrong here.

**Comment by parkhabit** [comment]
The page error seems to be now fixed. 
The issue was in the naming convention of best-evidence, bestEvidence as one word had to be used instead. As apostrophe considers a hyphenated word to be two separate words.
