### ISSUE TITLE
Best Evidence style guide

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence-site#24]
Add our Style Guide to our documentation:
<img width="555" alt="screen shot 2018-03-15 at 14 48 57" src="https://user-images.githubusercontent.com/4185328/37470800-3757bd14-2860-11e8-90c3-8379ba78a8e2.png">
<img width="543" alt="screen shot 2018-03-15 at 14 49 04" src="https://user-images.githubusercontent.com/4185328/37470799-373de222-2860-11e8-8ba4-567bb94758fb.png">
<img width="559" alt="screen shot 2018-03-15 at 14 49 11" src="https://user-images.githubusercontent.com/4185328/37470798-3727606a-2860-11e8-9e61-cda0fe282757.png">

**Comment by iteles** [comment]
The font is Poppins. https://fonts.google.com/specimen/Poppins

**Comment by RobStallion** [comment]
@iteles I'm not sure if these colours are correct. The primary and secondary colours do not appear to be in the designs at all. Any thoughts?

**Comment by parkhabit** [comment]
@iteles It seems that the font given in this style guide poppins, may be incorrect. 
This is the invision font that we were given :
![screen shot 2018-03-15 at 16 24 20](https://user-images.githubusercontent.com/16639540/37476577-68deb6d2-286d-11e8-8066-3c5a40c84a1e.png)
And this is the poppins font:
![screen shot 2018-03-15 at 16 24 11](https://user-images.githubusercontent.com/16639540/37476582-6b278aa4-286d-11e8-8a4d-e7aed9b5bbc6.png)
At first, we thought there was a difference in font weighting, but you can see that the g is different. Can we get confirmation on which font is correct?

**Comment by iteles** [comment]
Aaaaaah, ok, it looks like the 'Style Guide' tab in the Sketch file was a test rather than the actual style guide (though @Jen-Harris can confirm).

From what I can see:
+ Fonts:
  + Titles: Work Sans Bold
  + Text: Work sans regular
+ Text colour:
  + Brighter red is the accent hex DE1E2E
  + Darker red is hex 7C2935 or you could try the Secondary hex too

Let me know if you need anything else, I have the sketch file open!

**Comment by Jen-Harris** [comment]
Hello yes sorry the Sketch files were a WIP and then I didn't correct them - I can do this if it's helpful?

What you've said is correct though @iteles for both the fonts and colours. 

Sorry for the confusion!!

**Comment by iteles** [comment]
No problem @Jen-Harris, if we have the correct ones already then let's leave it for now and then once you look at the app itself for the additional half day we can get it all up to date!
