### ISSUE TITLE
Create a template for stories email

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence-site#31]
Create an new email template for the stories email

**Comment by RobStallion** [comment]
Do we have any specific text/layout for the email?

**Comment by iteles** [comment]
@RobStallion What are you sending out right now?

**Comment by RobStallion** [comment]
@iteles it currently looks like this 
```
Hi admin!

You've just received a message from: username useremail

The following was written: test
```

**Comment by iteles** [comment]
If we can differentiate between the stories and the other contact form I would suggest:

```
Subject: A BestEvidence story has just been submitted

Hi admin

A story has just been submitted by 'username useremail'

Story title: 'story title'

The following was written:
'text starting on next line'
```

Note: the text should reflect line breaks!
