### ISSUE TITLE
Setup S3

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#5]
set up s3 so that we have somewhere to store images

**Comment by RobStallion** [comment]
We have created an s3 account with the best.evidence.dev@gmail.com email account which seems to be working as expected. 

Next we are going to set up the mongo database with mlab, see issue #6, so we can save data to our own database. 

Leaving this issue open until we can confirm that both s3 and mlab are working together as expected.

**Comment by parkhabit** [comment]
Added test picture to S3, going to try and render it on the site to make sure all is working.

**Comment by parkhabit** [comment]
Images can be added through the CMS. Couldn't render an image directly from S3, although we can add one to S3.
