### ISSUE TITLE
Set up mLab 

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#6]
Set up mLab with Heroku so that we have a separate database from the existing Quodl database

**Comment by RobStallion** [comment]
Have confirmed that mLab is now working with our site. Added an admin user to the mongo db with 
```
APOS_MONGODB_URI=mongodb://<username>:<password>@<mLabURL>/<username>
(this will be provided by heroku when you add mLab)
```
and have been able to log in.

Closing issue
