### ISSUE TITLE
Testimonials section at the bottom of the homepage

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence-site#7]
As a visitor to the site,
I would like to see a section of 1-2 line testimonials at the bottom of the homepage
So that people can immediately see how great the app is!

## Acceptance Criteria
We don't have styling yet, so this is a little more difficult but:
+ [ ] 3 testimonials across the bottom of the page, 2-3 lines each at most
+ [ ] Content of these must be editable through the CMS
+ [ ] Each must have a little photo circle next to the quote

**Comment by RobStallion** [comment]
closing in favour of #16
