### ISSUE TITLE
Contact form | Email notifications

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence-site#8]
As a site admin, when someone uses the contact form, I would like there to be an email sent to me so that I don't have to keep remembering to check this.

## Acceptance Criteria
+ [x] When a contact form is filled in, an email is sent to an email address with the contents of the form (sender, subject and message)
+ [x] The content of this email needs to be readable - i.e. Formatted (line breaks for example) as it was entered by the user
+ [x] Emails can be sent to multiple admin recipients

See https://github.com/cul-2016/site/issues/42 for research already done on this

**Comment by RobStallion** [comment]
Have verified the project email [here](https://eu-west-1.console.aws.amazon.com/ses/home?region=eu-west-1#verified-senders-email:) on SES and we are now able to send emails using the npm module [sendemail](https://github.com/dwyl/sendemail). 

Next steps

- Test sending email to multiple recipients 
- Stop `apostrophe` from submitting the form data if there was an error sending the email. 
- Ensure that line breaks are displayed correctly in the email
