### ISSUE TITLE
Contact form | Expand details section

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence-site#9]
At the moment, the contact form looks a bit odd:
<img width="802" alt="screen shot 2018-03-08 at 13 27 08" src="https://user-images.githubusercontent.com/4185328/37153445-a8be86ae-22d4-11e8-953d-0adeac1e450a.png">

As a visitor, I would like to have more space to input the content of my Message (Details) so that the user experience is friendlier.

**Comment by iteles** [comment]
Making this a higher priority to research as it's possible that this may have a knock-on effect for the rest of the contact form issues.

**Comment by parkhabit** [comment]
In Lib/modules/messages/index.js added 
```
{
name:"details",
type:"string",
textarea:true
}
```
This changes the amount of lines that can be displayed horizontally from one to many. This can now be styled through CSS.

**Comment by iteles** [comment]
@parkhabit @RobStallion Would be good to get into the habit of pushing this to heroku so it can be tested live as well as locally: https://best-evidence-site.herokuapp.com/contact

<img width="1146" alt="screen shot 2018-03-09 at 13 51 01" src="https://user-images.githubusercontent.com/4185328/37210527-f33558f8-23a0-11e8-97bc-45dd97fd8e5c.png">

Time to add an issue for automatic deployment from master to heroku?

**Comment by parkhabit** [comment]
@iteles The site is now updated on Heroku so you are able to go to https://best-evidence-site.herokuapp.com/contact click on 'add submit message' and view the contact form.

**Comment by iteles** [comment]
👍 
<img width="920" alt="screen shot 2018-03-28 at 15 06 14" src="https://user-images.githubusercontent.com/4185328/38034163-97ab67a4-3299-11e8-867c-87d0e70586d3.png">
